### PR TITLE
Update ppdippstr.py

### PR DESCRIPTION
**Pull request by LAfricain**
New strings internationalized for the ppd.

### CODE REVIEW

**Comment by zdohnal** [comment]
Hi,
I'm sorry for being late - the patch looks generally ok to me, but would you mind keeping english in commentary at l. 96?
And is this merge request different than #109 ? It looks quite similar to me.

**Comment by LAfricain** [comment]
> I'm sorry for being late

No problem :)

> And is this merge request different than #109 ?

I should be very similar, but I'm a newbie with git, and I had difficulties why the pull, rebase... For this reason I begun from scratch.
Thanks for the merge. Now I will translate the po.

**Comment by zdohnal** [comment]
Sorry, I didn't merge it yet - would you mind correcting the issue mentioned in my previous comment?

**Comment by LAfricain** [comment]
Oh yes sorry.
I'll come back.

**Comment by LAfricain** [comment]
Correction done, pull request #109 should be merge (not yet #104 )

**Comment by LAfricain** [comment]
Hello,
Please update the po files for new strings in ppdippstr.py.Thanks

**Pull request closed without merging**
